### ISSUE TITLE
[Question] How to compile for Android?

### ISSUE THREAD

**Issue by DonZheng** [ConorSheehan1/spelling-bee#19]
Hi @ConorSheehan1 ,

Accidentally bumped into your site and found this very great piece of work.  I can't help wondering what motivates you to keep on updating the app?

Also, I wonder if the spelling puzzle game can be compiled for android devices? My kids would love this. (I don't really want them to go to nyt and get exposed to ugly politics)

Cheers

**Comment by ConorSheehan1** [comment]
Hi @DonZheng 

Glad you're enjoying the game! I play almost daily myself, and so do some of my friends and family, so that keeps me motivated. I'm hoping to improve it a bit over the holidays.

I think it's possible but I've never compiled a vue app to android myself. You could look into something like Cordova, Electron, or Ionic if you want to give it a go. I don't think I'll have time to try it myself unfortunately.

Cheers
